apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:Ymo4X5wuqxPrWCnuzo7JTcNbPO6LaH7YC+yY56zudDjVu6y5Yz62rmJPjznGBWwzu0cZGzhJzT4pkY7cNMClGsks6aL+zhTjNacGDVOHcRugd5iEaRB6/DjSVwdDkUgKHcNlujM78U5/NgXwHQIq8TWlEvHY2p83OPCIh1nGwIX/3F/kxdZYgw3UkKzW1LwaqFDcFGhltquilXaVIg4UQA+vVCauJEu1DpolSI7RnQYR0PvYMUdYcj58VmCcjQhrHSk/JEjthzI6CzmAyEHgJO5YKgzxX/81Xt0NNyPa2CxTvEI9MI0ApoBzMFc=,iv:bbmZA12OHQdDwDXFXE+8y48pvmAF6EDhbQeAJzmQ6Dk=,tag:QPvz7MJN7wRkPNSuXl74wQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5djJheEhiYlBhM3c3YmhU
            Nm9iL21TRG5KZUprSGsvMDZkOTE3LzhqYndvClh5Y0pwSUYzK1E1TFhjZmpFU0pH
            bTdJb3c2VDJpQS9NWlgra0NyN0Y5OWMKLS0tIFFlRXYzQXpBUTlzTDd6WWhTdFd6
            dnpRcFV3cml4SmU4bHQ5Rkx5eFFWbWsKL7Yvkp15MYgx6CrffmVHpkqRiCtO42iZ
            nEgvA5CN8KrvC6JS2jyMqGQu234ZEoKcj1YI09XjJpZsOe0Qb+Wjsw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zh3gd0gyffz7k40lve4h04ssm5h75rqpq2te59cgxws3nk5ys5zq34ypsq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-22T20:17:05Z"
    mac: ENC[AES256_GCM,data:I35TaDbJ4p5d1Qov/xDwiiNyvBU/Ddn3mvfqERtloCobJ4D4itbqtOEpo0jzHSAlKOl+n61fDQ/VGTloeONeYX9HFSijpDDE0C+ONGRpg3AVSvUdeEG+L7RAZoggIkQsJl55jKrtcPMND0t4wI8cs5hNqhyMPRqmdeKBviZuGgs=,iv:Nlto1K3v+OgVs+0nltgc9cungK1lYhs1eZAVfTvaWzM=,tag:8iReNLDEwc2xfbScYzUmww==,type:str]
    version: 3.13.1
