[tools]
flux2 = "latest"
helm = "latest"
k9s = "latest"
kubectl = "latest"
kubectx = "latest"
kubelogin = "latest"
kubens = "latest"
sops = "latest"
talosctl = "latest"

[env]
CLUSTER_NAME = "cerebro"
KUBECONFIG = "./kubeconfig"
