apiVersion: v1
kind: Secret
metadata:
    name: velero-s3-credentials
    namespace: velero
stringData:
    cloud: ENC[AES256_GCM,data:Qm8GO9b0eQDomlgE+eoKIqq/qw0UO89CQ7Tjklh7y1hgqDzCWYTEcToSEp6HnpFdTEut3/fw1SPfzI5DNRgLE2fzN7zh2oq+ibz/yL1f8tOuOTCVX4hbsAaP7z7Rj7RRuiHqFIPhmQS4pKjEp+aDnMSQwsswITqnCd51pWrybQY55/9Gif7iPlBqFbQcFwXx8o9oyQ==,iv:u6/8dd5Vc+giAM2bYrzVryW6y/LY1W8C3KtotoeSdNw=,tag:gG4xzQsHWjtEQnyvGXAHnw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMVRlWldFSTV5cGtERTcv
            dnU2SXJ3dldBMVRkMXpTVWhUbE5nSkhLSVRZCk8vMkdJMXBrNUY3aVEyaGZOTzFz
            SVpZRTVpVkdac3p4c1AyUWZXT0s4cTgKLS0tIDhta21raGhVdXV5S3pBMmMzWGJh
            b3c5M2lQVFBPMmVCVGc4U0Y3amdxQ2sKFekRRzpZh+1Lo4lCmqFzbBnVJBJJsaaD
            /8IiGNqa0kgzSfglqUgy++ovI6a5H6ykS3+yz3WWs4CYJqLquLQgGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zh3gd0gyffz7k40lve4h04ssm5h75rqpq2te59cgxws3nk5ys5zq34ypsq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-04T12:59:03Z"
    mac: ENC[AES256_GCM,data:6curbG2yvUEp+NxduhEkbr7JSpA/peI/msNFb6b/sABCq6cCTzwYUO95oC403FCLRo+2FYmLZoTTTDMAFNSagm9j7R2n8ayvUZq5Ga656O7xfcFhZfh/A3VedJeCi6sCVAiLU3TncbzbCRXPZkNsXjsc0LsYHzkD1TizVo7nL0A=,iv:SPiSFihgl8vNDgD5U/14CbMu87QmG5Jgo3DzLzRBWNU=,tag:ITa6fdNaoRVlCy2F4OMwtw==,type:str]
    version: 3.13.1
