apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:rZAXcMxA0Mo=,iv:NU1AzdoXLhXi2tmj30+IZPWTMQAukACovzKGp0xhprk=,tag:UMwHlUuWDqyCyvvl+UKzYQ==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:N1FbmmHg/H4M9I7FmbaMTizKCYk=,iv:lmc8PA7TLbfEOSU6sXiZ+INgxWlhLwaLJcWIa29FzuQ=,tag:C6OBGii3IGjcScb9PT+e0Q==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBybjk4Uncvbk9LK1BRV21s
            cklQOE1XT2pvWDI1dTZ6R09VSjNSL0FGUTNnCnpNVjJ5OGo4MjJNNjl2aVo3amFl
            NVVkUGRjRjRZNEZSTUx0akN1a2VtMVEKLS0tIFVOWEVQY2FEVVpkTEFTemg5ajY0
            Q28xOUdzUFpXSWVNanZaSCtoOCtRVEkKzcfQwFuZYRtZCVkx3u1A46hYDKNPss0z
            RuhZs8n4o/+w3P2mmsQ6M2qbdQ6/QOBmqVRJceqRwnL4Nr8Dvq0Amw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zh3gd0gyffz7k40lve4h04ssm5h75rqpq2te59cgxws3nk5ys5zq34ypsq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-22T20:39:15Z"
    mac: ENC[AES256_GCM,data:SpykOo1y4vS2XONk7Oo6c1ar2X/tkfvEn4KaKs1uSldeY78/gs5k9oyGWMuzy8a+DaoxTTEGX5zwlAgutYqORVUQlz3Rums5gSnPlTFOtcni9JgMOEWtZwprv1OBn/ODta5NNbId5Q4TtogC9XTvdqia0wDiHAp4IywRro9Scvs=,iv:u/owUHLGJK1piqYU2YzhZYnRdSQbNJ0igaWF7DtNg8U=,tag:qjzWRsmWvnAmI9qJdlE6/g==,type:str]
    version: 3.13.1
