apiVersion: v1
kind: Secret
metadata:
    name: cert-tracker-db-credentials
stringData:
    username: ENC[AES256_GCM,data:ySciCOmhA1HTTjE=,iv:UMuDOFtHe6U3gsEE3J4FGqadoFrB7o7SLMLY2J91Wzs=,tag:Opf5wlWMBDYyYawi2cchoA==,type:str]
    password: ENC[AES256_GCM,data:WeyoNfXgLt2Rk3I=,iv:ijmDyx8SLRdRMP4w5QI+opWQv3cYbvEKzNuPhMn/FHY=,tag:Td3gbT283PyzBPC35475PA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbncyYmdrb2lYSmhUUlEv
            WFR4NXBNcUJnVFhPUmVWMW1MSnZlUS9KclFNCmJ1ZitWT2VKWGJHR0JxeWNYZXhY
            a280Y2JsZDhYcWFSbkRHL09Da3hmR1kKLS0tIE5UODVGQXFLVklqc2RRcEVTVW40
            K1ZyelBhVDZJam9rdHlGb0xyamVMR0EKmg0hJl6XlNaETjwBgHgH53Z0J5ynvxF/
            jP/+MVXFQIhdOs+LGk4YLfiRrFqR2A1wOmlqgaN5dB0IMCdR9gu/VQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zh3gd0gyffz7k40lve4h04ssm5h75rqpq2te59cgxws3nk5ys5zq34ypsq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T10:31:01Z"
    mac: ENC[AES256_GCM,data:Y7fYhemDKaQ47LaCFL4j0Z1/RDuJhw78phBzxoq4oAVWrfg8U5fu5cenTH/7asDpusZm1PsDn9iIR4N5zi/Lo5aWfznx1UsV8686CKkoIOvmYgcUbsOXFMnqJJyMu7+Wojv4i57t+0I2jWrrshLKSBHK7un9Yu/i1TYR3Jgm0Q8=,iv:KN9Wp/hxkxXkZQIxlOMlSq4ZxAnV8cSMTa8rR8ZyvuI=,tag:0OH3tM1TCaNbTYUVe6P5EQ==,type:str]
    version: 3.13.1
