apiVersion: v1
kind: Secret
metadata:
    name: cert-tracker-env
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:pHkqaGXcig126utkes5NPFKA2Y7eEGz43urhfvBgza3ntYOUABQiaEtJbboc8SlvRDqVzma+X5wDbUD2w1uZOXD5xKjODA==,iv:pi/dJHajWZPUdHBd/9GS7WxcNG+TgdDdWutl75T5tDI=,tag:/Ow3LI3KWuyhTKh4wYBOHA==,type:str]
    BASIC_AUTH_USER: ENC[AES256_GCM,data:a7r/GsQ=,iv:8DimLka6ddlgxbzxhs+BElub8MegrrWJwtBJqXo2Yqo=,tag:iS8DiaqPteqHHOmCdjRIyA==,type:str]
    BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:g35j05/pRkciovg=,iv:2/lILxqZqwCyHqwhjNyjEoYFs8xS1B8AxTEtntdj+7k=,tag:BVjpxmpz6WUuQ0oaPhFwDg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSGRPWjAxa0k0QjA2SEFT
            aFJwRlVLcXM4N20xRWdENjliN1BNdVBrOUhFCkhjMHRDOGVrUHh2bXlJSUdEN1VN
            SWozUEgwckdwUFZRNWpMWmZGMHVZR3MKLS0tIDluNzNYUE5aTkpmRTF3cEFqZ0g5
            emZWSlFIelJqYkNBOUpqTFcwQkZPYUEKJVI6uhqaJPzSXScTEHPspQV/iXv9b3bF
            RDJ0By8qHzAR+wBwEqGSKAMUotrQalbYWb3gROtsfDUw2dEOik5r1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zh3gd0gyffz7k40lve4h04ssm5h75rqpq2te59cgxws3nk5ys5zq34ypsq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T08:01:55Z"
    mac: ENC[AES256_GCM,data:TxvwJdBU0kKt98e90VDnJpYG3AYGIt+zw1EgddW1AgBBZH6E0TcGi/Vac1rDW50V6i1DO8K3bMDKTUjDbppughlDKzbYFwdSf0e/KiNSO6aiWSbDd76zsLqR392rF86HU2GH8OZ6N2zOuLMFi9cqlsv8xJgV4IG/le+5HyVbFPI=,iv:jKE7QtUBxQRrStm60UBFsxv6gjg4XNXuXeXiMiRDMBs=,tag:WKAMCh88mkDpG1iP9+wmLg==,type:str]
    version: 3.13.1
