apiVersion: v1
kind: Secret
metadata:
    name: cert-tracker-db-credentials
stringData:
    username: ENC[AES256_GCM,data:P3K7+8UjyxXc4Fw=,iv:UbMmvlfWZ0aBS3cgbhn807daJ0DhnBDovPyUQLD+psY=,tag:WxGjHPzqCQUa3ysJiqQmtA==,type:str]
    password: ENC[AES256_GCM,data:gfQy7igXxBFkpDs=,iv:fm5YFw7sCHF05xpecRJBX0oV38mwBCg6kHai30mJ+gw=,tag:MvvN5XNeGb+kb7gvO5ilIg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMzByVWNnZVdDdVFsQVcv
            T05yZkN2T1h2Wi96dWYxUHpMN2pVd0lXa1VnCmgwZ25pUUk5UXpHQlc3c0pjS3Rl
            aHJvWWpwMVR1T0VRMmhuYmlLbk51UncKLS0tIHF0OFNRVElVVFVUa2VIZ3UzR0hC
            QVNGdzJWaVJyT2F5Z1BxSGFqR1NibTQKiS6xqDtlxrzCKJdtleh7KJo1ipmDRTCO
            YctSQvVkcEZtRcr3sl6oI34MsNNFY9R9dFLmBgX5IB1KZmtTy3M+lA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zh3gd0gyffz7k40lve4h04ssm5h75rqpq2te59cgxws3nk5ys5zq34ypsq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T08:02:50Z"
    mac: ENC[AES256_GCM,data:lT4eL4Msa3vkpmrt/55/79WEtUiyT7MfO4TfWEEZj4lMrBhFvzJbtY3/pS2JPplGdxH5fpWx6skyv8fQpRe8vYI1RPIAPtRBaNIT1Bi42LE/E4nG5vB4pju1ogeCMbk/EJv/M2L9Md4hc8ae56Spmf7SdDjfPWr57WGDg7CAfJk=,iv:o8mmsWBIyl0jCtk1yKqGDNfDplbb/fKIIqNkZMshD3w=,tag:GESOBrgEVAQn3n3q2k04tA==,type:str]
    version: 3.13.1
