apiVersion: v1
kind: Secret
metadata:
    name: cert-tracker-env
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:HpO4zKxoi9gFLlmyG0GTdvG81dBytGxqgw8PFI9kZanL/UMHPo4SZtaqRu8CXDwt3+EX7CwZb4rk7ldt0hCathRMOHoOWQYO,iv:Ycb1fzMWfcZDITJMHQl4r9VJLhVWhF2sfbXhsU6LXxo=,tag:QakWqiRmMMl/aIHwHC/djQ==,type:str]
    BASIC_AUTH_USER: ENC[AES256_GCM,data:9X7syM8=,iv:Sz6S5pCs5+arFld8m9WpHSqt/8H6nfFDhyNGUFktdQE=,tag:9/8QUWzYg32cx/SmijFGxw==,type:str]
    BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:kFEHeYF5jXMpHLc=,iv:bQh9zJzSO5zyiqm5Fqky8bM5DMpcrzW1ce10IuIiTwU=,tag:vFP913+oA5FQS78J1TVivA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZjFyaC9XQ2ppcVoxRVpQ
            anNRUnZkZ05DNENBTmdWNkVVTHpiTjg4UUFNCmZTemlkUVBzNzlqdlBQT21uVlVk
            ZVUxWUppL3NsbER1Z0xqUGp4SGpGS1UKLS0tIFVyb2psbm9sM1JVUFBYd01raXZF
            Q3dqcXlSV2pzd0FmUmY1cWNxMld3TWcKCLvzUwtHxMomoqLOTm/hAioV7Dfibp0y
            wGDKvrTze7FjlC8WOeogCwUSRwzNIFO4dysjO3UxW6fLEn3b6I4NPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zh3gd0gyffz7k40lve4h04ssm5h75rqpq2te59cgxws3nk5ys5zq34ypsq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T10:30:51Z"
    mac: ENC[AES256_GCM,data:aH+3pVIYdZ0w1N/K8mi6VIYUOtkaeoYhTpODRpBytxo+QExFE5u/X4YXoTIuVNJLNUbvcBVWDbNRz+8Vqg6V1rtxGNtfnVXHcPIsSeROdp6hZvPYlH+lUET8SY/R+8C97aVJ6/xQ6Hv89+kj9PDmBmsO9c3Ufp5Edd8SiPBsnVU=,iv:MvlIsGKQ7hOo+ImTHteZSrRdellhyVlQIhC251Ht6NA=,tag:/cYD9n3lZaFWttFYZk1Y5g==,type:str]
    version: 3.13.1
