apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-tracker

resources:
  - ../../base/cert-tracker
  - cloudflare.yaml
  - cf-secret.yaml
  - cert-tracker-env-secret.yaml
  - cert-tracker-db-credentials-secret.yaml
