apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:MbzCag8=,iv:n7wCpJjT0TKnSnb2RRunOMeTvCj9F9gVjUU7Ok8fuAc=,tag:tsoB821qPdP9ZKD3FlNtig==,type:str]
    admin-password: ENC[AES256_GCM,data:koI0NGlGk7+e8YvY3w==,iv:1Uolo1dT4cfmBTExkOrLp8tVywJiLs5JxgvkRARPT1U=,tag:sVN7ugHB9F5KhFPuBuNJuA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQytVWjVGOWV5Q1plaHBs
            ejdEZFJKaFlWY1JrNUxwYnhaU0tWYnFjd3lnCmFtVHpSbWhldHI4YlV1R1dBQUFP
            ZXBLMjMxZXdTc2hra0FNRlYxTDN0NTgKLS0tIGIrMXJLTFNBQnZEeTMrWnRuc21X
            OVlISWw4THlzYjN3M3NZcVJEbTc2UmMKrIrEpVu9vo/3CeWgZcAb4TBAfOawrF0b
            RMsAJ7TbulKzmwlKyM536EyQJToTRJMA3csIuNg6pufMhn8hLNs6PQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zh3gd0gyffz7k40lve4h04ssm5h75rqpq2te59cgxws3nk5ys5zq34ypsq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-23T05:54:52Z"
    mac: ENC[AES256_GCM,data:v2x88h8kKwzk81qL+v31jmdryDeI/aVDM0UZFJ7wLhq97U1KdaTtVxq6gPIYMhHIZVMh5fiQcLxWvmzeuaj8DE6K9bzBAsmnRqncwadEFSxv9Q7Cm2gNJ1rSv6T8mEDTFzeI1lA9R+tINyydMhGX7aGOZ2m2eUjQKznngPbUiCE=,iv:JKVBG+tj/MvFlF6JZlyflocdkkOlTelew8E65TVPi90=,tag:ysnla6LTzVbYtbvgsidxyw==,type:str]
    version: 3.13.1
