apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
spec:
  interval: 30m

  chart:
    spec:
      chart: traefik
      version: "40.1.0"
      sourceRef:
        kind: HelmRepository
        name: traefik

  install:
    createNamespace: true

  values:
    deployment:
      replicas: 1

    ingressClass:
      enabled: true
      isDefaultClass: true

    service:
      type: LoadBalancer

    logs:
      general:
        level: INFO

    additionalArguments:
      - "--api.dashboard=true"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

    providers:
      kubernetesCRD:
        enabled: true
      kubernetesIngress:
        enabled: true
