apiVersion: v1
kind: Secret
metadata:
    name: kube-prometheus-stack-values
    namespace: monitoring
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:WWkUeAVIWpkK5r8u26AAv+h5K9lq/tpeXQ3GD1dgpxhxPDa9I0GuX0bWG1q49sQTfFI32+MPdPZaTIVtGrJzi5SMSptqVZxVSbex/feJdFhUjsAQBFRuT2UuzNfRDy4c7oD46WrHfUcwGduvhg==,iv:rMNug0F+817GyyzZA5MHz++nY0eGpD1eRJuHU1GYrwk=,tag:Ve1iELwFuSNX8Q7fyibjYA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWFkyUmcySStwdEY2alFt
            d3VpZlphQUp4ZmlXNHUzYTl1WGd1Ym9wNVJNCnhTclV3NzFvdGhxZmJOTElIRksw
            WmlEUUtGb1dMUVk2c2Y5Q0lCNnhzVTgKLS0tIFQyN090aVlDUU9ZNWdZRnYzWk1z
            b29vblJ1Z2kwakN6M1gwcU9FeTNML1UK9JTicetrY56tqWs3A1Utucc1o/dttnJX
            DMbymFx52KE+Y1sIAPQOwL4Fp6JZN9UWAFxjGphIE1b7v4KRfwTHuQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zh3gd0gyffz7k40lve4h04ssm5h75rqpq2te59cgxws3nk5ys5zq34ypsq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-26T14:19:59Z"
    mac: ENC[AES256_GCM,data:tOxTYBFoDOfnIakRhKd5WhXIID/BHvmcLnwJxQ5/ywB4wu/3hLNfH/TlLg9G4w7MwJwsqYqIUpwsC1qZOibeJNwOarptLSDiev9T0GqK9m5lOj83S9EINUXWDEfOZfeEznBS8xMtmDdaNUo5k1JwM02uYw/Gcmt98R4QJxl+0ig=,iv:Qg2C7YHz3RNpAPqLqc19p9vMb186qf2+dQ2NlMKCRFA=,tag:GsgDcJNQkzZespvdR8b6fA==,type:str]
    version: 3.13.1
