apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-tracker-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-tracker-frontend
  template:
    metadata:
      labels:
        app: cert-tracker-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/rickywaldt/cert-tracker-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
