apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-tracker

resources:
  - namespace.yaml
  - cluster.yaml
  - deployment-api.yaml
  - deployment-frontend.yaml
  - cronjob.yaml
  - service-api.yaml
  - service-frontend.yaml
